(function(){
window.HCC_I18N_EXTRA=window.HCC_I18N_EXTRA||{};
window.HCC_I18N_EXTRA.es={
  nav:{picker:'Selector',image:'Imagen',wheel:'Rueda',chart:'Tabla',library:'Biblioteca de colores',converter:'Convertidor',rgbToHex:'RGB a Hex',hexToRgb:'Hex a RGB',tools:'Herramientas',contrast:'Comprobador de contraste',mixer:'Mezclador de colores',names:'Nombres',colorNames:'Nombres de colores',minecraft:'Minecraft',bukkit:'Bukkit',roblox:'Roblox'},
  page:{crumbColor:'Codigos de color',crumbTools:'Herramientas de color',pickerTitle:'Selector de color',pickerDesc:'Explora colores, genera armonias, convierte valores y exporta codigos de color en una herramienta sencilla.',imageTitle:'Selector de color de imagen',imageDesc:'Sube una imagen, toma colores de sus pixeles, extrae una paleta y exporta codigos.',wheelTitle:'Rueda de color',wheelDesc:'Elige colores en una rueda, crea paletas, genera armonias y exporta codigos.',chartTitle:'Tabla de colores',chartDesc:'Con tablas Tailwind CSS, diseno plano, Material Design y colores web seguros, puedes encontrar el esquema perfecto para tu sitio o app.',libraryTitle:'Biblioteca de colores',libraryDesc:'Explora mas de 100 tonos y copia codigos de color para tus proyectos.',rgbTitle:'RGB a Hex',rgbDesc:'Convierte cualquier valor RGB a codigo Hex y consulta sus valores HSL, HSV y CMYK.',hexTitle:'Hex a RGB',hexDesc:'Convierte cualquier codigo Hex a RGB y consulta sus valores HSL, HSV, OKLCH y CMYK.',contrastTitle:'Comprobador de contraste',contrastDesc:'Comprueba la relacion de contraste entre primer plano y fondo para disenos legibles y accesibles.',mixerTitle:'Mezclador de colores',mixerDesc:'Mezcla dos colores y genera tonos combinados para paletas, interfaces y proyectos creativos.'},
  ui:{copy:'Copiar',random:'Paleta aleatoria',exportColors:'Exportar colores',chooseHarmony:'Elegir armonia...',history:'Historial',clear:'Borrar',noColors:'Aun no hay colores',copied:'Copiado al portapapeles',uploadImage:'Subir imagen',uploadHint:'Haz clic o suelta una imagen para tomar colores.',wheelNote:'Haz clic o arrastra en la rueda para elegir un color.',colorHarmonies:'Armonias de color',colorVariations:'Variaciones de color',colorConversion:'Conversion de color',contrastChecker:'Comprobador de contraste',blindness:'Simulador de daltonismo',exportCodes:'Exportar codigos de color',copyCodes:'Copiar codigos',prefix:'prefijo',search:'Buscar colores'}
};
window.HCC_I18N_EXTRA.fr={
  nav:{picker:'Selecteur',image:'Image',wheel:'Roue',chart:'Nuancier',library:'Bibliotheque de couleurs',converter:'Convertisseur',rgbToHex:'RGB vers Hex',hexToRgb:'Hex vers RGB',tools:'Outils',contrast:'Verificateur de contraste',mixer:'Melangeur de couleurs',names:'Noms',colorNames:'Noms de couleurs',minecraft:'Minecraft',bukkit:'Bukkit',roblox:'Roblox'},
  page:{crumbColor:'Codes couleur',crumbTools:'Outils couleur',pickerTitle:'Selecteur de couleur',pickerDesc:'Parcourez les couleurs, genereez des harmonies, convertissez les valeurs et exportez les codes couleur dans un outil simple.',imageTitle:'Selecteur de couleur d image',imageDesc:'Importez une image, prelevez des couleurs dans les pixels, extrayez une palette et exportez les codes.',wheelTitle:'Roue chromatique',wheelDesc:'Choisissez des couleurs sur une roue, creez des palettes, genereez des harmonies et exportez les codes.',chartTitle:'Nuancier',chartDesc:'Avec les nuanciers Tailwind CSS, flat design, Material Design et web safe, trouvez facilement le schema parfait pour votre site ou application.',libraryTitle:'Bibliotheque de couleurs',libraryDesc:'Explorez plus de 100 nuances et copiez les codes couleur pour vos projets.',rgbTitle:'RGB vers Hex',rgbDesc:'Convertissez n importe quelle valeur RGB en code Hex et consultez les valeurs HSL, HSV et CMYK.',hexTitle:'Hex vers RGB',hexDesc:'Convertissez n importe quel code Hex en RGB et consultez les valeurs HSL, HSV, OKLCH et CMYK.',contrastTitle:'Verificateur de contraste',contrastDesc:'Verifiez le contraste entre premier plan et arriere-plan pour des designs lisibles et accessibles.',mixerTitle:'Melangeur de couleurs',mixerDesc:'Melangez deux couleurs et genereez des tons pour palettes, interfaces et projets creatifs.'},
  ui:{copy:'Copier',random:'Palette aleatoire',exportColors:'Exporter les couleurs',chooseHarmony:'Choisir une harmonie...',history:'Historique',clear:'Effacer',noColors:'Aucune couleur pour le moment',copied:'Copie dans le presse-papiers',uploadImage:'Importer une image',uploadHint:'Cliquez ou deposez une image pour prelever des couleurs.',wheelNote:'Cliquez ou faites glisser sur la roue pour choisir une couleur.',colorHarmonies:'Harmonies de couleurs',colorVariations:'Variations de couleur',colorConversion:'Conversion de couleur',contrastChecker:'Verificateur de contraste',blindness:'Simulateur de daltonisme',exportCodes:'Exporter les codes couleur',copyCodes:'Copier les codes',prefix:'prefixe',search:'Rechercher des couleurs'}
};
window.HCC_I18N_EXTRA.de={
  nav:{picker:'Picker',image:'Bild',wheel:'Farbrad',chart:'Farbtafel',library:'Farbbibliothek',converter:'Konverter',rgbToHex:'RGB zu Hex',hexToRgb:'Hex zu RGB',tools:'Werkzeuge',contrast:'Kontrastpruefer',mixer:'Farbmischer',names:'Namen',colorNames:'Farbnamen',minecraft:'Minecraft',bukkit:'Bukkit',roblox:'Roblox'},
  page:{crumbColor:'Farbcodes',crumbTools:'Farbwerkzeuge',pickerTitle:'Farbwaehler',pickerDesc:'Durchsuche Farben, erstelle Harmonien, wandle Werte um und exportiere Farbcodes in einem einfachen Werkzeug.',imageTitle:'Bild-Farbwaehler',imageDesc:'Lade ein Bild hoch, waehle Farben aus Pixeln, extrahiere eine Palette und exportiere Codes.',wheelTitle:'Farbrad',wheelDesc:'Waehle Farben im Farbrad, erstelle Paletten, generiere Harmonien und exportiere Codes.',chartTitle:'Farbtafel',chartDesc:'Mit Tailwind CSS, Flat Design, Material Design und Web-Safe-Farbtafeln findest du das passende Farbschema fuer Website oder App.',libraryTitle:'Farbbibliothek',libraryDesc:'Entdecke ueber 100 Farbtoene und kopiere Farbcodes fuer deine Projekte.',rgbTitle:'RGB zu Hex',rgbDesc:'Wandle jeden RGB-Wert in einen Hex-Farbcode um und sieh passende HSL-, HSV- und CMYK-Werte.',hexTitle:'Hex zu RGB',hexDesc:'Wandle jeden Hex-Farbcode in RGB um und sieh passende HSL-, HSV-, OKLCH- und CMYK-Werte.',contrastTitle:'Kontrastpruefer',contrastDesc:'Pruefe das Kontrastverhaeltnis zwischen Vordergrund und Hintergrund fuer lesbare, zugaengliche Designs.',mixerTitle:'Farbmischer',mixerDesc:'Mische zwei Farben und erzeuge abgestufte Toene fuer Paletten, Oberflaechen und kreative Projekte.'},
  ui:{copy:'Kopieren',random:'Zufallspalette',exportColors:'Farben exportieren',chooseHarmony:'Harmonie waehlen...',history:'Verlauf',clear:'Loeschen',noColors:'Noch keine Farben',copied:'In die Zwischenablage kopiert',uploadImage:'Bild hochladen',uploadHint:'Klicke oder lege ein Bild ab, um Farben zu waehlen.',wheelNote:'Klicke oder ziehe im Farbrad, um eine Farbe zu waehlen.',colorHarmonies:'Farbharmonien',colorVariations:'Farbvariationen',colorConversion:'Farbkonvertierung',contrastChecker:'Kontrastpruefer',blindness:'Farbsinn-Simulator',exportCodes:'Farbcodes exportieren',copyCodes:'Codes kopieren',prefix:'Praefix',search:'Farben suchen'}
};
window.HCC_I18N_EXTRA.pt={
  nav:{picker:'Seletor',image:'Imagem',wheel:'Roda',chart:'Tabela',library:'Biblioteca de cores',converter:'Conversor',rgbToHex:'RGB para Hex',hexToRgb:'Hex para RGB',tools:'Ferramentas',contrast:'Verificador de contraste',mixer:'Misturador de cores',names:'Nomes',colorNames:'Nomes de cores',minecraft:'Minecraft',bukkit:'Bukkit',roblox:'Roblox'},
  page:{crumbColor:'Codigos de cor',crumbTools:'Ferramentas de cor',pickerTitle:'Seletor de cor',pickerDesc:'Explore cores, gere harmonias, converta valores e exporte codigos de cor em uma ferramenta simples.',imageTitle:'Seletor de cor de imagem',imageDesc:'Envie uma imagem, escolha cores dos pixels, extraia uma paleta e exporte codigos.',wheelTitle:'Roda de cores',wheelDesc:'Escolha cores em uma roda, crie paletas, gere harmonias e exporte codigos.',chartTitle:'Tabela de cores',chartDesc:'Com tabelas Tailwind CSS, flat design, Material Design e web safe, encontre o esquema perfeito para seu site ou app.',libraryTitle:'Biblioteca de cores',libraryDesc:'Explore mais de 100 tons e copie codigos de cor para seus projetos.',rgbTitle:'RGB para Hex',rgbDesc:'Converta qualquer valor RGB para codigo Hex e veja valores HSL, HSV e CMYK.',hexTitle:'Hex para RGB',hexDesc:'Converta qualquer codigo Hex para RGB e veja valores HSL, HSV, OKLCH e CMYK.',contrastTitle:'Verificador de contraste',contrastDesc:'Verifique a taxa de contraste entre primeiro plano e fundo para designs legiveis e acessiveis.',mixerTitle:'Misturador de cores',mixerDesc:'Misture duas cores e gere tons combinados para paletas, interfaces e projetos criativos.'},
  ui:{copy:'Copiar',random:'Paleta aleatoria',exportColors:'Exportar cores',chooseHarmony:'Escolher harmonia...',history:'Historico',clear:'Limpar',noColors:'Ainda sem cores',copied:'Copiado para a area de transferencia',uploadImage:'Enviar imagem',uploadHint:'Clique ou solte uma imagem para escolher cores.',wheelNote:'Clique ou arraste na roda para escolher uma cor.',colorHarmonies:'Harmonias de cor',colorVariations:'Variacoes de cor',colorConversion:'Conversao de cor',contrastChecker:'Verificador de contraste',blindness:'Simulador de daltonismo',exportCodes:'Exportar codigos de cor',copyCodes:'Copiar codigos',prefix:'prefixo',search:'Pesquisar cores'}
};
})();
