(function(){
window.HCC_LEGAL_PAGES={
    'about':{title:'About',path:'/about/',hero:'Learn who maintains Color Codex and how these color tools are designed for practical web, UI, and creative work.',sections:[
      {h:'Who we are',p:['Color Codex is a practical color tools website for designers, developers, creators, and students who need quick access to color picking, conversion, palettes, charts, contrast checks, and color reference tables.','The site is maintained as an independent web project focused on clean interface design, useful browser-based tools, and clear color information that can be copied into real projects.']},
      {h:'What this site provides',p:['The tools on this site help you choose colors, convert color formats, inspect contrast, mix colors, browse color names, and export codes for CSS, design systems, and creative workflows.','All core tools are designed to run in the browser so you can work quickly without installing software.']},
      {h:'Accuracy and updates',p:['Color formulas, conversion results, and accessibility checks are implemented with care, but color appearance can vary by display, browser, operating system, and color profile. Use exported values as a reliable technical reference and verify critical design decisions in your own environment.','We continue improving the site structure, interface, and reference content so the tools remain useful, fast, and easy to understand.']}
    ]},
    'privacy-policy':{title:'Privacy Policy',path:'/privacy-policy/',hero:'Read how Color Codex handles basic usage data, local browser storage, uploaded images, and third-party services.',sections:[
      {h:'Overview',p:['This Privacy Policy explains how Color Codex handles information when you use this website. By using the site, you agree to the practices described here.']},
      {h:'Information you provide',p:['Most tools work directly in your browser. If you type a color value, upload an image, or interact with a picker, that information is used to provide the tool result. Uploaded images are processed locally in the browser for color picking features and are not intentionally stored by this site.']},
      {h:'Local storage',p:['The site may use browser storage such as localStorage to remember preferences, language selection, color history, and other interface settings. You can clear this data in your browser settings at any time.']},
      {h:'Analytics and logs',p:['Basic technical data may be processed by hosting, analytics, security, or performance services, such as page URL, device type, browser type, approximate region, referring page, and error information. This data helps keep the site secure, fast, and reliable.']},
      {h:'Cookies and third-party services',p:['If analytics, ads, embedded services, or security services are used, those providers may set cookies or process data according to their own policies. You can control cookies through your browser settings.']},
      {h:'Data sharing',p:['We do not sell personal information. Information may be processed by service providers that help operate, secure, analyze, or improve the site, or when required by law.']},
      {h:'Children',p:['This site is intended for general audiences and is not directed to children under the age required by applicable privacy law.']},
      {h:'Changes to this policy',p:['This policy may be updated as the site changes. The updated version will be posted on this page.']}
    ]},
    'terms-of-service':{title:'Terms of Service',path:'/terms-of-service/',hero:'Review the terms that apply when you use Color Codex tools, pages, color data, and exported code.',sections:[
      {h:'Acceptance of terms',p:['By accessing or using Color Codex, you agree to these Terms of Service. If you do not agree, do not use the site.']},
      {h:'Use of the tools',p:['You may use the color tools, generated values, palettes, and exported code for personal, educational, and commercial projects. You are responsible for checking that any color choices, contrast decisions, and exported values are appropriate for your own use case.']},
      {h:'No professional advice',p:['The site provides color tools and reference information. It does not provide legal, accessibility compliance, branding, or professional design advice. Important accessibility or production decisions should be reviewed in your own workflow.']},
      {h:'Intellectual property',p:['The site design, interface, text, and code are protected by applicable intellectual property laws unless otherwise stated. You may not copy, resell, or redistribute the site itself as a competing service without permission.']},
      {h:'Acceptable use',p:['Do not misuse the site, attempt to disrupt its operation, scrape it aggressively, bypass security, upload harmful content, or use it in a way that violates laws or the rights of others.']},
      {h:'Availability',p:['The site is provided as is and as available. Features may change, break, be removed, or become temporarily unavailable. We do not guarantee uninterrupted or error-free operation.']},
      {h:'Limitation of liability',p:['To the fullest extent permitted by law, Color Codex is not liable for losses or damages resulting from use of the site, tool outputs, downtime, errors, or third-party services.']},
      {h:'Changes to these terms',p:['These terms may be updated from time to time. Continued use of the site after changes means you accept the updated terms.']}
    ]}
  };
window.HCC_LEGAL_PAGE_I18N={
    zh:{
      'about':{title:'关于我们',path:'/about/',hero:'了解 Color Codex 的维护者，以及这些颜色工具如何服务于网页、界面和创意工作。',sections:[{h:'我们是谁',p:['Color Codex 是一个实用的颜色工具网站，面向设计师、开发者、创作者和学生。','本站专注于清晰界面、浏览器内工具和可直接用于真实项目的颜色信息。']},{h:'本站提供什么',p:['你可以使用本站选择颜色、转换格式、检查对比度、混合颜色、浏览颜色名称并导出代码。','核心工具在浏览器中运行，便于快速完成 CSS、设计系统和创意工作。']},{h:'准确性和更新',p:['颜色转换和无障碍检查经过谨慎实现，但颜色显示仍可能受设备、浏览器和色彩配置影响。','我们会持续改进界面、工具和参考内容，让网站保持实用、快速且易懂。']}]},
      'privacy-policy':{title:'隐私政策',path:'/privacy-policy/',hero:'了解 Color Codex 如何处理基础使用数据、本地浏览器存储、上传图片和第三方服务。',sections:[{h:'概述',p:['本隐私政策说明你使用本站时 Color Codex 如何处理信息。使用本站即表示你同意此处描述的做法。']},{h:'你提供的信息',p:['大多数工具直接在浏览器中运行。你输入的颜色值、上传的图片或取色操作只用于生成工具结果。','上传图片用于本地取色处理，本站不会有意存储这些图片。']},{h:'本地存储',p:['本站可能使用 localStorage 保存偏好设置、语言选择、颜色历史和界面状态。你可以随时在浏览器设置中清除这些数据。']},{h:'分析与日志',p:['托管、安全、分析或性能服务可能处理页面 URL、设备类型、浏览器类型、大致地区、来源页面和错误信息。','这些数据用于维护网站安全、快速和可靠。']},{h:'Cookie 和第三方服务',p:['如果使用分析、广告、嵌入或安全服务，相关提供商可能按其政策设置 Cookie 或处理数据。你可以通过浏览器设置管理 Cookie。']},{h:'数据共享',p:['我们不会出售个人信息。服务提供商可能为运营、安全、分析或法律要求处理必要信息。']},{h:'儿童',p:['本站面向一般受众，并非面向适用隐私法律规定年龄以下的儿童。']},{h:'本政策的变更',p:['随着网站变化，本政策可能更新。更新后的版本会发布在本页面。']}]},
      'terms-of-service':{title:'服务条款',path:'/terms-of-service/',hero:'查看使用 Color Codex 工具、页面、颜色数据和导出代码时适用的条款。',sections:[{h:'接受条款',p:['访问或使用 Color Codex 即表示你同意这些服务条款。如果你不同意，请不要使用本站。']},{h:'工具使用',p:['你可以将颜色工具、生成值、调色板和导出代码用于个人、教育和商业项目。','你需要自行确认颜色选择、对比度决策和导出值适合你的用途。']},{h:'非专业建议',p:['本站提供颜色工具和参考信息，不提供法律、无障碍合规、品牌或专业设计建议。重要决策应在你的工作流程中复核。']},{h:'知识产权',p:['除非另有说明，本站设计、界面、文本和代码受适用知识产权法律保护。未经许可，不得将本站本身复制、转售或重新分发为竞争服务。']},{h:'可接受的使用方式',p:['请勿滥用本站、干扰运行、过度抓取、绕过安全措施、上传有害内容，或以违法或侵犯他人权利的方式使用。']},{h:'可用性',p:['本站按现状和可用状态提供。功能可能变更、失效、移除或暂时不可用。']},{h:'责任限制',p:['在法律允许的最大范围内，Color Codex 不对使用本站、工具输出、停机、错误或第三方服务造成的损失负责。']},{h:'条款变更',p:['这些条款可能不时更新。变更后继续使用本站即表示你接受更新后的条款。']}]}
    },
    ja:{
      'about':{title:'概要',path:'/about/',hero:'Color Codex の運営方針と、実用的な Web・UI・制作作業のためのカラー工具について説明します。',sections:[{h:'私たちについて',p:['Color Codex は、デザイナー、開発者、制作者、学生のための実用的なカラー工具サイトです。','見やすいインターフェース、ブラウザー上で動くツール、実際の制作に使いやすいカラー情報を重視しています。']},{h:'提供する機能',p:['色の選択、形式変換、コントラスト確認、色の混合、カラー名の参照、コードの書き出しができます。','主要な機能はブラウザー内で動作し、CSS、デザインシステム、制作作業にすばやく利用できます。']},{h:'正確性と更新',p:['変換式やアクセシビリティ確認は慎重に実装していますが、色の見え方は端末、ブラウザー、OS、カラープロファイルによって変わる場合があります。','サイト構造、UI、参照情報は継続的に改善します。']}]},
      'privacy-policy':{title:'プライバシーポリシー',path:'/privacy-policy/',hero:'Color Codex が基本的な利用データ、ローカル保存、アップロード画像、第三者サービスをどのように扱うかを説明します。',sections:[{h:'概要',p:['このポリシーは、サイト利用時に Color Codex が情報をどのように扱うかを説明します。']},{h:'入力される情報',p:['ほとんどのツールはブラウザー内で動作します。入力した色、アップロード画像、ピッカー操作は結果を表示するために使われます。','アップロード画像は色取得のためにローカル処理され、意図的に保存されません。']},{h:'ローカル保存',p:['言語、設定、色履歴などを保存するため localStorage を使用することがあります。ブラウザー設定から削除できます。']},{h:'分析とログ',p:['ホスティング、セキュリティ、分析、性能改善のため、URL、端末、ブラウザー、地域、参照元、エラー情報などが処理される場合があります。']},{h:'Cookie と第三者サービス',p:['分析、広告、埋め込み、安全サービスを使用する場合、各提供者が独自の方針に従って Cookie やデータを処理することがあります。']},{h:'データ共有',p:['個人情報を販売しません。運営、安全、分析、法令対応のために必要な範囲でサービス提供者が処理する場合があります。']},{h:'子ども',p:['本サイトは一般利用者向けであり、適用法で定められた年齢未満の子どもを対象としていません。']},{h:'変更',p:['このポリシーは更新される場合があり、更新版はこのページに掲載されます。']}]},
      'terms-of-service':{title:'利用規約',path:'/terms-of-service/',hero:'Color Codex のツール、ページ、色データ、書き出しコードを利用する際の条件です。',sections:[{h:'規約への同意',p:['Color Codex にアクセスまたは利用することで、この利用規約に同意したものとみなされます。']},{h:'ツールの利用',p:['カラー工具、生成値、パレット、書き出しコードは個人、教育、商用プロジェクトに利用できます。','利用目的に合うかどうかは利用者自身で確認してください。']},{h:'専門的助言ではありません',p:['本サイトはカラー工具と参考情報を提供しますが、法務、アクセシビリティ認証、ブランド、専門的デザイン助言ではありません。']},{h:'知的財産',p:['サイトのデザイン、UI、文章、コードは特に明記がない限り知的財産権により保護されます。']},{h:'許容される利用',p:['運営妨害、過度な取得、セキュリティ回避、有害コンテンツの送信、違法利用は禁止します。']},{h:'可用性',p:['本サイトは現状有姿で提供され、機能は変更、停止、削除される場合があります。']},{h:'責任の制限',p:['法令で認められる範囲で、本サイト利用、出力、停止、エラー、第三者サービスによる損害について責任を負いません。']},{h:'規約の変更',p:['規約は随時更新される場合があります。変更後の継続利用は更新規約への同意を意味します。']}]}
    },
    ko:{
      'about':{title:'소개',path:'/about/',hero:'Color Codex를 운영하는 방식과 웹, UI, 창작 작업을 위한 색상 도구를 소개합니다.',sections:[{h:'우리는 누구인가',p:['Color Codex는 디자이너, 개발자, 제작자, 학생을 위한 실용적인 색상 도구 사이트입니다.','깔끔한 인터페이스, 브라우저 기반 도구, 실제 프로젝트에 복사해 사용할 수 있는 명확한 색상 정보를 중시합니다.']},{h:'제공 기능',p:['색상 선택, 형식 변환, 대비 확인, 색상 혼합, 색상 이름 탐색, 코드 내보내기를 제공합니다.','핵심 도구는 브라우저에서 실행되어 CSS, 디자인 시스템, 창작 작업에 빠르게 사용할 수 있습니다.']},{h:'정확성과 업데이트',p:['색상 변환과 접근성 확인은 신중하게 구현되지만 표시 결과는 기기, 브라우저, OS, 색상 프로필에 따라 달라질 수 있습니다.','사이트 구조, 인터페이스, 참고 콘텐츠를 계속 개선합니다.']}]},
      'privacy-policy':{title:'개인정보 처리방침',path:'/privacy-policy/',hero:'Color Codex가 기본 사용 데이터, 브라우저 저장소, 업로드 이미지, 제3자 서비스를 처리하는 방식을 설명합니다.',sections:[{h:'개요',p:['이 방침은 사이트 이용 시 Color Codex가 정보를 처리하는 방식을 설명합니다.']},{h:'제공하는 정보',p:['대부분의 도구는 브라우저에서 직접 작동합니다. 입력한 색상, 업로드 이미지, 피커 조작은 결과 제공에 사용됩니다.','업로드 이미지는 색상 선택을 위해 로컬에서 처리되며 의도적으로 저장되지 않습니다.']},{h:'로컬 저장소',p:['언어, 설정, 색상 기록 등은 localStorage에 저장될 수 있으며 브라우저 설정에서 삭제할 수 있습니다.']},{h:'분석과 로그',p:['호스팅, 보안, 분석, 성능 서비스를 통해 URL, 기기, 브라우저, 대략적 지역, 참조 페이지, 오류 정보가 처리될 수 있습니다.']},{h:'쿠키와 제3자 서비스',p:['분석, 광고, 임베드, 보안 서비스가 사용되면 각 제공자가 자체 정책에 따라 쿠키나 데이터를 처리할 수 있습니다.']},{h:'데이터 공유',p:['개인정보를 판매하지 않습니다. 운영, 보안, 분석, 법적 요구에 필요한 범위에서 서비스 제공자가 처리할 수 있습니다.']},{h:'아동',p:['이 사이트는 일반 사용자를 대상으로 하며 적용 법률상 보호 연령 미만 아동을 대상으로 하지 않습니다.']},{h:'변경',p:['이 방침은 업데이트될 수 있으며 변경된 내용은 이 페이지에 게시됩니다.']}]},
      'terms-of-service':{title:'서비스 약관',path:'/terms-of-service/',hero:'Color Codex 도구, 페이지, 색상 데이터, 내보낸 코드를 사용할 때 적용되는 약관입니다.',sections:[{h:'약관 동의',p:['Color Codex에 접속하거나 사용하면 이 서비스 약관에 동의하는 것입니다.']},{h:'도구 사용',p:['색상 도구, 생성값, 팔레트, 내보낸 코드는 개인, 교육, 상업 프로젝트에 사용할 수 있습니다.','색상 선택과 출력값이 목적에 적합한지는 사용자가 확인해야 합니다.']},{h:'전문 조언 아님',p:['이 사이트는 색상 도구와 참고 정보를 제공하며 법률, 접근성 인증, 브랜딩, 전문 디자인 조언을 제공하지 않습니다.']},{h:'지적 재산',p:['사이트 디자인, 인터페이스, 텍스트, 코드는 별도 명시가 없는 한 지적재산권 보호를 받습니다.']},{h:'허용되는 사용',p:['사이트 오용, 운영 방해, 과도한 수집, 보안 우회, 유해 콘텐츠 업로드, 불법 사용을 금지합니다.']},{h:'가용성',p:['사이트는 있는 그대로 제공되며 기능은 변경, 중단, 제거될 수 있습니다.']},{h:'책임 제한',p:['법이 허용하는 범위에서 사이트 사용, 출력, 중단, 오류, 제3자 서비스로 인한 손해에 대해 책임지지 않습니다.']},{h:'약관 변경',p:['약관은 수시로 업데이트될 수 있으며 변경 후 계속 사용하면 업데이트된 약관에 동의한 것입니다.']}]}
    },
    es:{
      'about':{title:'Acerca de',path:'/about/',hero:'Conoce quién mantiene Color Codex y cómo estas herramientas de color ayudan al trabajo web, UI y creativo.',sections:[{h:'Quiénes somos',p:['Color Codex es un sitio práctico de herramientas de color para diseñadores, desarrolladores, creadores y estudiantes.','El proyecto se centra en una interfaz clara, herramientas en el navegador e información de color fácil de usar en proyectos reales.']},{h:'Qué ofrece este sitio',p:['Puedes elegir colores, convertir formatos, comprobar contraste, mezclar colores, explorar nombres de colores y exportar código.','Las herramientas principales funcionan en el navegador para trabajar rápido con CSS, sistemas de diseño y proyectos creativos.']},{h:'Precisión y actualizaciones',p:['Las conversiones y comprobaciones se implementan con cuidado, pero la apariencia puede variar según pantalla, navegador, sistema y perfil de color.','Seguimos mejorando la estructura, la interfaz y el contenido de referencia.']}]},
      'privacy-policy':{title:'Política de privacidad',path:'/privacy-policy/',hero:'Lee cómo Color Codex gestiona datos básicos de uso, almacenamiento local, imágenes subidas y servicios de terceros.',sections:[{h:'Resumen',p:['Esta política explica cómo Color Codex trata la información cuando usas el sitio.']},{h:'Información que proporcionas',p:['La mayoría de herramientas funcionan en tu navegador. Los colores, imágenes y acciones del selector se usan para mostrar resultados.','Las imágenes subidas se procesan localmente para seleccionar colores y no se almacenan intencionadamente.']},{h:'Almacenamiento local',p:['El sitio puede usar localStorage para recordar idioma, preferencias, historial de colores y ajustes de interfaz.']},{h:'Analítica y registros',p:['Servicios de alojamiento, seguridad, analítica o rendimiento pueden procesar URL, dispositivo, navegador, región aproximada, referencia y errores.']},{h:'Cookies y terceros',p:['Si se usan analítica, anuncios, servicios integrados o seguridad, esos proveedores pueden usar cookies o datos según sus políticas.']},{h:'Compartición de datos',p:['No vendemos información personal. Proveedores de servicio pueden procesar datos para operar, proteger, analizar o cumplir requisitos legales.']},{h:'Menores',p:['Este sitio está dirigido a público general y no a menores protegidos por la ley de privacidad aplicable.']},{h:'Cambios',p:['Esta política puede actualizarse y la versión nueva se publicará en esta página.']}]},
      'terms-of-service':{title:'Términos del servicio',path:'/terms-of-service/',hero:'Revisa los términos aplicables al usar las herramientas, páginas, datos de color y código exportado de Color Codex.',sections:[{h:'Aceptación de términos',p:['Al acceder o usar Color Codex aceptas estos términos. Si no estás de acuerdo, no uses el sitio.']},{h:'Uso de las herramientas',p:['Puedes usar herramientas, valores, paletas y código exportado en proyectos personales, educativos y comerciales.','Eres responsable de verificar que los resultados sean adecuados para tu caso.']},{h:'Sin asesoramiento profesional',p:['El sitio ofrece herramientas e información de referencia, no asesoramiento legal, de accesibilidad, marca o diseño profesional.']},{h:'Propiedad intelectual',p:['El diseño, interfaz, textos y código están protegidos salvo indicación contraria.']},{h:'Uso aceptable',p:['No abuses del sitio, interrumpas su funcionamiento, lo extraigas agresivamente, evadas seguridad o lo uses ilegalmente.']},{h:'Disponibilidad',p:['El sitio se ofrece tal cual y puede cambiar, fallar, eliminarse o no estar disponible temporalmente.']},{h:'Limitación de responsabilidad',p:['En la medida permitida por la ley, Color Codex no responde por pérdidas derivadas del uso del sitio, resultados, errores o servicios de terceros.']},{h:'Cambios en los términos',p:['Estos términos pueden actualizarse. El uso continuado implica aceptación de los términos actualizados.']}]}
    },
    fr:{
      'about':{title:'À propos',path:'/about/',hero:'Découvrez qui maintient Color Codex et comment ces outils couleur servent le travail web, UI et créatif.',sections:[{h:'Qui sommes-nous',p:['Color Codex est un site pratique d’outils couleur pour designers, développeurs, créateurs et étudiants.','Le projet privilégie une interface claire, des outils dans le navigateur et des informations couleur utilisables dans de vrais projets.']},{h:'Ce que propose le site',p:['Vous pouvez choisir des couleurs, convertir des formats, vérifier le contraste, mélanger des couleurs, parcourir des noms et exporter du code.','Les outils principaux fonctionnent dans le navigateur pour travailler rapidement avec CSS, systèmes de design et projets créatifs.']},{h:'Précision et mises à jour',p:['Les conversions et vérifications sont réalisées avec soin, mais l’apparence peut varier selon l’écran, le navigateur, le système et le profil couleur.','Nous améliorons continuellement la structure, l’interface et le contenu de référence.']}]},
      'privacy-policy':{title:'Politique de confidentialité',path:'/privacy-policy/',hero:'Découvrez comment Color Codex traite les données d’usage, le stockage local, les images importées et les services tiers.',sections:[{h:'Aperçu',p:['Cette politique explique comment Color Codex traite les informations lorsque vous utilisez le site.']},{h:'Informations fournies',p:['La plupart des outils fonctionnent dans votre navigateur. Les couleurs, images et actions du sélecteur servent à fournir les résultats.','Les images importées sont traitées localement pour la sélection de couleur et ne sont pas volontairement stockées.']},{h:'Stockage local',p:['Le site peut utiliser localStorage pour mémoriser la langue, les préférences, l’historique des couleurs et les réglages d’interface.']},{h:'Analyses et journaux',p:['Des services d’hébergement, sécurité, analyse ou performance peuvent traiter URL, appareil, navigateur, région approximative, référent et erreurs.']},{h:'Cookies et tiers',p:['Si des services d’analyse, publicité, intégration ou sécurité sont utilisés, ils peuvent traiter cookies ou données selon leurs propres politiques.']},{h:'Partage des données',p:['Nous ne vendons pas d’informations personnelles. Des prestataires peuvent traiter des données pour exploiter, sécuriser, analyser ou respecter la loi.']},{h:'Enfants',p:['Ce site vise un public général et non les enfants protégés par la législation applicable.']},{h:'Modifications',p:['Cette politique peut être mise à jour et la nouvelle version sera publiée sur cette page.']}]},
      'terms-of-service':{title:'Conditions d’utilisation',path:'/terms-of-service/',hero:'Consultez les conditions applicables aux outils, pages, données couleur et code exporté de Color Codex.',sections:[{h:'Acceptation',p:['En accédant à Color Codex ou en l’utilisant, vous acceptez ces conditions.']},{h:'Utilisation des outils',p:['Vous pouvez utiliser les outils, valeurs, palettes et codes exportés pour des projets personnels, éducatifs et commerciaux.','Vous devez vérifier que les résultats conviennent à votre usage.']},{h:'Pas de conseil professionnel',p:['Le site fournit des outils couleur et des références, pas de conseil juridique, conformité accessibilité, marque ou design professionnel.']},{h:'Propriété intellectuelle',p:['Le design, l’interface, les textes et le code sont protégés sauf indication contraire.']},{h:'Usage acceptable',p:['N’abusez pas du site, ne perturbez pas son fonctionnement, n’extrayez pas massivement, ne contournez pas la sécurité et ne l’utilisez pas illégalement.']},{h:'Disponibilité',p:['Le site est fourni tel quel et peut changer, tomber en panne, être retiré ou devenir temporairement indisponible.']},{h:'Limitation de responsabilité',p:['Dans la limite autorisée par la loi, Color Codex n’est pas responsable des pertes liées à l’utilisation, aux résultats, erreurs ou services tiers.']},{h:'Changements',p:['Ces conditions peuvent être mises à jour. La poursuite de l’utilisation vaut acceptation des conditions mises à jour.']}]}
    },
    de:{
      'about':{title:'Über uns',path:'/about/',hero:'Erfahre, wer Color Codex pflegt und wie diese Farbwerkzeuge für Web-, UI- und Kreativarbeit gedacht sind.',sections:[{h:'Wer wir sind',p:['Color Codex ist eine praktische Website mit Farbwerkzeugen für Designer, Entwickler, Kreative und Studierende.','Das Projekt legt Wert auf klare Oberflächen, browserbasierte Werkzeuge und Farbinformationen, die in echten Projekten nutzbar sind.']},{h:'Was diese Website bietet',p:['Du kannst Farben wählen, Formate umwandeln, Kontrast prüfen, Farben mischen, Farbnamen durchsuchen und Code exportieren.','Die wichtigsten Werkzeuge laufen im Browser und helfen schnell bei CSS, Designsystemen und kreativer Arbeit.']},{h:'Genauigkeit und Updates',p:['Konvertierungen und Prüfungen werden sorgfältig umgesetzt, dennoch kann die Darstellung je nach Display, Browser, System und Farbprofil variieren.','Wir verbessern Struktur, Oberfläche und Referenzinhalte fortlaufend.']}]},
      'privacy-policy':{title:'Datenschutzerklärung',path:'/privacy-policy/',hero:'Lies, wie Color Codex Nutzungsdaten, lokalen Speicher, hochgeladene Bilder und Drittanbieter verarbeitet.',sections:[{h:'Überblick',p:['Diese Datenschutzerklärung beschreibt, wie Color Codex Informationen bei der Nutzung der Website verarbeitet.']},{h:'Von dir bereitgestellte Informationen',p:['Die meisten Werkzeuge laufen direkt im Browser. Farben, Bilder und Picker-Interaktionen werden zur Ergebnisanzeige genutzt.','Hochgeladene Bilder werden lokal zur Farbauswahl verarbeitet und nicht absichtlich gespeichert.']},{h:'Lokaler Speicher',p:['Die Website kann localStorage nutzen, um Sprache, Einstellungen, Farbverlauf und Interface-Zustände zu speichern.']},{h:'Analyse und Protokolle',p:['Hosting-, Sicherheits-, Analyse- oder Leistungsdienste können URL, Gerät, Browser, ungefähre Region, Verweis und Fehlerdaten verarbeiten.']},{h:'Cookies und Drittanbieter',p:['Bei Analyse, Werbung, Einbettungen oder Sicherheitsdiensten können Anbieter Cookies oder Daten nach eigenen Richtlinien verarbeiten.']},{h:'Datenweitergabe',p:['Wir verkaufen keine personenbezogenen Daten. Dienstleister können Daten für Betrieb, Sicherheit, Analyse oder gesetzliche Anforderungen verarbeiten.']},{h:'Kinder',p:['Diese Website richtet sich an ein allgemeines Publikum und nicht an Kinder unter dem gesetzlich geschützten Alter.']},{h:'Änderungen',p:['Diese Erklärung kann aktualisiert werden; die neue Version wird auf dieser Seite veröffentlicht.']}]},
      'terms-of-service':{title:'Nutzungsbedingungen',path:'/terms-of-service/',hero:'Prüfe die Bedingungen für Werkzeuge, Seiten, Farbdaten und exportierten Code von Color Codex.',sections:[{h:'Annahme der Bedingungen',p:['Durch Zugriff auf oder Nutzung von Color Codex akzeptierst du diese Bedingungen.']},{h:'Nutzung der Werkzeuge',p:['Du darfst Werkzeuge, Werte, Paletten und exportierten Code für persönliche, schulische und kommerzielle Projekte nutzen.','Du bist verantwortlich zu prüfen, ob Ergebnisse für deinen Zweck geeignet sind.']},{h:'Keine professionelle Beratung',p:['Die Website bietet Farbwerkzeuge und Referenzen, aber keine Rechts-, Barrierefreiheits-, Marken- oder professionelle Designberatung.']},{h:'Geistiges Eigentum',p:['Design, Oberfläche, Texte und Code sind geschützt, sofern nicht anders angegeben.']},{h:'Zulässige Nutzung',p:['Missbrauch, Störung des Betriebs, aggressives Scraping, Sicherheitsumgehung, schädliche Inhalte und rechtswidrige Nutzung sind untersagt.']},{h:'Verfügbarkeit',p:['Die Website wird wie verfügbar bereitgestellt; Funktionen können sich ändern, ausfallen, entfernt werden oder vorübergehend nicht verfügbar sein.']},{h:'Haftungsbeschränkung',p:['Soweit gesetzlich zulässig haftet Color Codex nicht für Schäden durch Nutzung, Ausgaben, Fehler, Ausfälle oder Drittanbieter.']},{h:'Änderungen der Bedingungen',p:['Diese Bedingungen können aktualisiert werden. Weitere Nutzung bedeutet Zustimmung zu den aktualisierten Bedingungen.']}]}
    },
    pt:{
      'about':{title:'Sobre',path:'/about/',hero:'Saiba quem mantém o Color Codex e como estas ferramentas de cor ajudam no trabalho web, UI e criativo.',sections:[{h:'Quem somos',p:['Color Codex é um site prático de ferramentas de cor para designers, desenvolvedores, criadores e estudantes.','O projeto prioriza interface clara, ferramentas no navegador e informações de cor úteis para projetos reais.']},{h:'O que o site oferece',p:['Você pode escolher cores, converter formatos, verificar contraste, misturar cores, explorar nomes e exportar código.','As ferramentas principais rodam no navegador para agilizar CSS, sistemas de design e trabalhos criativos.']},{h:'Precisão e atualizações',p:['Conversões e verificações são implementadas com cuidado, mas a aparência pode variar por tela, navegador, sistema e perfil de cor.','Continuamos melhorando estrutura, interface e conteúdo de referência.']}]},
      'privacy-policy':{title:'Política de Privacidade',path:'/privacy-policy/',hero:'Leia como o Color Codex lida com dados básicos de uso, armazenamento local, imagens enviadas e serviços de terceiros.',sections:[{h:'Visão geral',p:['Esta política explica como o Color Codex trata informações quando você usa o site.']},{h:'Informações fornecidas',p:['A maioria das ferramentas funciona no navegador. Cores, imagens e interações são usadas para gerar resultados.','Imagens enviadas são processadas localmente para seleção de cores e não são armazenadas intencionalmente.']},{h:'Armazenamento local',p:['O site pode usar localStorage para lembrar idioma, preferências, histórico de cores e configurações de interface.']},{h:'Análises e registros',p:['Serviços de hospedagem, segurança, análise ou desempenho podem processar URL, dispositivo, navegador, região aproximada, referência e erros.']},{h:'Cookies e terceiros',p:['Se forem usados análise, anúncios, incorporações ou segurança, provedores podem processar cookies ou dados conforme suas políticas.']},{h:'Compartilhamento de dados',p:['Não vendemos informações pessoais. Prestadores podem processar dados para operar, proteger, analisar ou cumprir a lei.']},{h:'Crianças',p:['Este site é destinado ao público geral e não a crianças abaixo da idade protegida por lei aplicável.']},{h:'Alterações',p:['Esta política pode ser atualizada e a nova versão será publicada nesta página.']}]},
      'terms-of-service':{title:'Termos de Serviço',path:'/terms-of-service/',hero:'Revise os termos aplicáveis ao usar ferramentas, páginas, dados de cor e código exportado do Color Codex.',sections:[{h:'Aceitação dos termos',p:['Ao acessar ou usar o Color Codex, você aceita estes Termos de Serviço.']},{h:'Uso das ferramentas',p:['Você pode usar ferramentas, valores, paletas e código exportado em projetos pessoais, educacionais e comerciais.','Você é responsável por verificar se os resultados são adequados ao seu caso.']},{h:'Sem aconselhamento profissional',p:['O site fornece ferramentas e referências de cor, não aconselhamento jurídico, acessibilidade, marca ou design profissional.']},{h:'Propriedade intelectual',p:['Design, interface, textos e código são protegidos salvo indicação contrária.']},{h:'Uso aceitável',p:['Não abuse do site, interrompa sua operação, faça coleta agressiva, burle segurança, envie conteúdo nocivo ou use ilegalmente.']},{h:'Disponibilidade',p:['O site é fornecido no estado em que se encontra e pode mudar, falhar, ser removido ou ficar temporariamente indisponível.']},{h:'Limitação de responsabilidade',p:['Na extensão permitida por lei, o Color Codex não se responsabiliza por perdas relacionadas ao uso, resultados, erros ou terceiros.']},{h:'Alterações dos termos',p:['Estes termos podem ser atualizados. O uso contínuo significa aceitação dos termos atualizados.']}]}
    },
    ru:{
      'about':{title:'О проекте',path:'/about/',hero:'Узнайте, кто поддерживает Color Codex и как эти инструменты помогают в веб-, UI- и творческой работе.',sections:[{h:'Кто мы',p:['Color Codex — практический сайт цветовых инструментов для дизайнеров, разработчиков, создателей и студентов.','Проект делает акцент на понятном интерфейсе, инструментах в браузере и цветовой информации для реальных проектов.']},{h:'Что предлагает сайт',p:['Вы можете выбирать цвета, конвертировать форматы, проверять контраст, смешивать цвета, просматривать названия и экспортировать код.','Основные инструменты работают в браузере и помогают быстро работать с CSS, дизайн-системами и творческими задачами.']},{h:'Точность и обновления',p:['Конвертации и проверки реализованы аккуратно, но отображение цвета зависит от экрана, браузера, системы и цветового профиля.','Мы продолжаем улучшать структуру, интерфейс и справочные материалы.']}]},
      'privacy-policy':{title:'Политика конфиденциальности',path:'/privacy-policy/',hero:'Узнайте, как Color Codex обрабатывает базовые данные использования, локальное хранилище, загруженные изображения и сторонние сервисы.',sections:[{h:'Обзор',p:['Эта политика объясняет, как Color Codex обрабатывает информацию при использовании сайта.']},{h:'Предоставляемая информация',p:['Большинство инструментов работает в браузере. Цвета, изображения и действия пикера используются для вывода результата.','Загруженные изображения обрабатываются локально для выбора цвета и намеренно не сохраняются.']},{h:'Локальное хранилище',p:['Сайт может использовать localStorage для языка, настроек, истории цветов и состояния интерфейса.']},{h:'Аналитика и журналы',p:['Хостинг, безопасность, аналитика или производительность могут обрабатывать URL, устройство, браузер, примерный регион, источник и ошибки.']},{h:'Cookies и третьи стороны',p:['При использовании аналитики, рекламы, встроенных или защитных сервисов поставщики могут обрабатывать cookies или данные по своим правилам.']},{h:'Передача данных',p:['Мы не продаем персональные данные. Поставщики услуг могут обрабатывать данные для работы, безопасности, анализа или требований закона.']},{h:'Дети',p:['Сайт предназначен для широкой аудитории и не ориентирован на детей младше возраста, защищенного применимым законом.']},{h:'Изменения',p:['Политика может обновляться; новая версия будет опубликована на этой странице.']}]},
      'terms-of-service':{title:'Условия использования',path:'/terms-of-service/',hero:'Ознакомьтесь с условиями использования инструментов, страниц, цветовых данных и экспортированного кода Color Codex.',sections:[{h:'Принятие условий',p:['Получая доступ к Color Codex или используя его, вы соглашаетесь с этими условиями.']},{h:'Использование инструментов',p:['Инструменты, значения, палитры и экспортированный код можно использовать в личных, учебных и коммерческих проектах.','Вы отвечаете за проверку пригодности результатов для своей задачи.']},{h:'Не профессиональная консультация',p:['Сайт предоставляет цветовые инструменты и справочную информацию, но не юридические, доступностные, брендовые или профессиональные дизайн-рекомендации.']},{h:'Интеллектуальная собственность',p:['Дизайн, интерфейс, тексты и код защищены, если не указано иное.']},{h:'Допустимое использование',p:['Запрещены злоупотребление сайтом, нарушение работы, агрессивный сбор, обход защиты, вредный контент и незаконное использование.']},{h:'Доступность',p:['Сайт предоставляется как есть; функции могут изменяться, ломаться, удаляться или временно быть недоступными.']},{h:'Ограничение ответственности',p:['В пределах закона Color Codex не отвечает за убытки от использования сайта, результатов, ошибок, простоев или сторонних сервисов.']},{h:'Изменения условий',p:['Условия могут обновляться. Продолжение использования означает согласие с обновленными условиями.']}]}
    }
  };
delete window.HCC_LEGAL_PAGE_I18N.ru;
})();
