(function(){
  var shared=window.HCC_SHARED||{};
  var clamp=shared.clamp,clear=shared.clear,block=shared.block,textNode=shared.textNode,t=shared.t,tx=shared.tx,cleanHex=shared.cleanHex,copyText=shared.copyText,hexToRgb=shared.hexToRgb,rgbToHex=shared.rgbToHex,rgbToHsl=shared.rgbToHsl,rgbToHsv=shared.rgbToHsv,rgbToOklch=shared.rgbToOklch,hslToRgb=shared.hslToRgb,lum=shared.lum,labMix=shared.labMix,setFromRgb=shared.setFromRgb,syncColorState=shared.syncColorState,render=shared.render,setHeroText=shared.setHeroText,clearTopNav=shared.clearTopNav,setRoute=shared.setRoute,openExport=shared.openExport,exportSvg=shared.exportSvg,trackColorBars=shared.trackColorBars,ensureLibraryData=shared.ensureLibraryData,ensureNameData=shared.ensureNameData,ensureChartData=shared.ensureChartData;
  var chartPicked=shared.chartPicked||{};
  function librarySections(){return shared.getLibrarySections?shared.getLibrarySections():[]}
  function namePages(){return shared.getNamePages?shared.getNamePages():{}}
  function chartDefs(){return shared.getChartDefs?shared.getChartDefs():[]}
  function setActiveRoute(v){if(shared.setActiveRoute)shared.setActiveRoute(v)}
  function chooseLibraryColor(hex,copyValue,recordColor){var rgb=hexToRgb(hex);if(rgb)setFromRgb(rgb);if(recordColor){recordClickedHex(hex,copyValue||('#'+cleanHex(hex)))}else{copyText(copyValue||('#'+cleanHex(hex)))}}
  function recordClickedHex(hex,copyValue){var fn=window.HCC_SHARED&&window.HCC_SHARED.recordClickedHex;if(fn)return fn(hex,copyValue);if(hex){copyText(copyValue||('#'+cleanHex(hex)))}}
  function appendNameTable(page,mount,rows,title){var section=block('section','hcc-name-section');if(title){section.appendChild(textNode('h2',tx(title)))}var table=block('table','hcc-names-table '+(page.type==='colorNames'?'':'hcc-format-table')),thead=block('thead'),tr=block('tr'),tbody=block('tbody');page.headers.forEach(function(h){tr.appendChild(textNode('th',tx(h)))});thead.appendChild(tr);table.appendChild(thead);rows.forEach(function(r){var row=block('tr');if(page.type==='colorNames'){var dotCell=block('td'),dot=block('span','hcc-name-dot'),hex='#'+r[1];dot.style.backgroundColor=hex;dot.onclick=function(){recordClickedHex(hex)};dotCell.appendChild(dot);row.appendChild(dotCell);row.appendChild(textNode('td',r[0]));[r[1],r[2],r[3]].forEach(function(v,i){var td=block('td'),span=textNode('span',v,'hcc-name-code');span.onclick=function(){copyText(i===0?'#'+v:v)};td.appendChild(span);row.appendChild(td)})}else if(page.type==='roblox'){var dotCell2=block('td'),dot2=block('span','hcc-name-dot'),hex2='#'+r[3];dot2.style.backgroundColor=hex2;dot2.onclick=function(){recordClickedHex(hex2,r[2])};dotCell2.appendChild(dot2);row.appendChild(dotCell2);row.appendChild(textNode('td',r[0]));[r[1],r[2]].forEach(function(v){var td=block('td'),span=textNode('span',String(v),'hcc-name-code');span.onclick=function(){copyText(String(v))};td.appendChild(span);row.appendChild(td)})}else{var dotCell3=block('td'),dot3=block('span','hcc-name-dot'),hex3='#'+r[3];dot3.style.backgroundColor=hex3;dot3.onclick=function(){recordClickedHex(hex3)};dotCell3.appendChild(dot3);row.appendChild(dotCell3);row.appendChild(textNode('td',r[0]));[r[1],r[2],r[3]].forEach(function(v,i){var td=block('td'),span=textNode('span',v,'hcc-name-code');span.onclick=function(){copyText(i===2?'#'+v:v)};td.appendChild(span);row.appendChild(td)})}tbody.appendChild(row)});table.appendChild(tbody);section.appendChild(table);mount.appendChild(section)}
  function colorNameSections(rows){var names={};rows.forEach(function(r){names[r[0]]=r});function take(title,list){return {title:title,rows:list.map(function(n){return names[n]}).filter(Boolean)}}return [take('Red HTML Color Names',['IndianRed','LightCoral','Salmon','DarkSalmon','LightSalmon','Crimson','Red','FireBrick','DarkRed']),take('Pink HTML Color Names',['Pink','LightPink','HotPink','DeepPink','MediumVioletRed','PaleVioletRed']),take('Orange HTML Color Names',['Orange','DarkOrange','Coral','Tomato','OrangeRed']),take('Yellow HTML Color Names',['Gold','Yellow','LightYellow','LemonChiffon','Khaki']),take('Purple HTML Color Names',['Lavender','Thistle','Plum','Violet','Orchid','Fuchsia','Magenta','Purple','RebeccaPurple','BlueViolet','Indigo']),take('Green HTML Color Names',['GreenYellow','Chartreuse','LawnGreen','Lime','LimeGreen','PaleGreen','LightGreen','MediumSpringGreen','SpringGreen','MediumSeaGreen','SeaGreen','ForestGreen','Green','DarkGreen']),take('Blue HTML Color Names',['Aqua','Cyan','LightCyan','PaleTurquoise','Aquamarine','Turquoise','MediumTurquoise','DarkTurquoise','CadetBlue','SteelBlue','LightSteelBlue','PowderBlue','LightBlue','SkyBlue','DeepSkyBlue','DodgerBlue','CornflowerBlue','RoyalBlue','Blue','MediumBlue','DarkBlue','Navy']),take('White HTML Color Names',['White','Snow','HoneyDew','MintCream','Azure','AliceBlue','GhostWhite','WhiteSmoke','Beige','Ivory']),take('Gray HTML Color Names',['Black','DarkSlateGray','DimGray','Gray','DarkGray','Silver','LightGray'])].filter(function(s){return s.rows.length})}
  function renderNamesTable(page,mount){if(page.type==='colorNames'){colorNameSections(page.rows).forEach(function(s){appendNameTable(page,mount,s.rows,s.title)})}else{appendNameTable(page,mount,page.rows,page.sectionTitle||'')}}
  function setNamePage(kind,syncHash){var pages=namePages();kind=pages[kind]?kind:'names';setActiveRoute(kind);if(syncHash){setRoute(kind,false)}var app=document.querySelector('.hcc-app'),page=pages[kind],intro=document.getElementById('hccNamesIntro'),heading=document.getElementById('hccNamesHeading'),mount=document.getElementById('hccNamesTable'),activeId=kind==='minecraft'?'hccNavNamesMinecraftItem':(kind==='bukkit'?'hccNavNamesBukkitItem':(kind==='roblox'?'hccNavNamesRobloxItem':'hccNavNamesColorItem'));app.className='hcc-app names-mode';clearTopNav();document.getElementById('hccNavNames').className='active';document.getElementById(activeId).className='active';setHeroText(tx(page.crumb||t('page.crumbColor')),tx(page.title),tx(page.hero||''));clear(heading);if(page.listTitle){heading.appendChild(textNode('h2',tx(page.listTitle)))}clear(intro);clear(mount);render();renderNamesTable(page,mount)}
  function renderLibrary(){var sections=librarySections(),mount=document.getElementById('hccLibraryList'),q=(document.getElementById('hccLibrarySearch').value||'').toLowerCase().trim(),shown=0;clear(mount);sections.forEach(function(section){var rows=section.rows.filter(function(r){return !q||r[0].toLowerCase().indexOf(q)>=0||r[1].toLowerCase().indexOf(q)>=0||section.title.toLowerCase().indexOf(q)>=0});if(!rows.length)return;shown+=rows.length;var wrap=block('section','hcc-library-section'),h=textNode('h3',tx(section.title)),tableWrap=block('div','hcc-library-table-wrap'),table=block('table','hcc-library-table'),thead=block('thead'),tr=block('tr'),tbody=block('tbody');['Color','Name','Hex code','RGB code','HSL code'].forEach(function(label){tr.appendChild(textNode('th',tx(label)))});thead.appendChild(tr);table.appendChild(thead);rows.forEach(function(r){var row=block('tr'),hex=cleanHex(r[1]),dotCell=block('td'),dot=block('span','hcc-library-dot'),name=textNode('span',r[0],'hcc-library-name');dot.style.backgroundColor='#'+hex;dot.onclick=function(){chooseLibraryColor(hex,null,true)};dotCell.appendChild(dot);row.appendChild(dotCell);var nameTd=block('td');name.onclick=function(){chooseLibraryColor(hex,r[0])};nameTd.appendChild(name);row.appendChild(nameTd);[hex,r[2],r[3]].forEach(function(v,i){var td=block('td'),code=textNode('span',v,'hcc-library-code');code.onclick=function(){chooseLibraryColor(hex,i===0?'#'+hex:v)};td.appendChild(code);row.appendChild(td)});tbody.appendChild(row)});table.appendChild(tbody);tableWrap.appendChild(table);wrap.appendChild(h);wrap.appendChild(tableWrap);mount.appendChild(wrap)});if(!shown){mount.appendChild(textNode('div',tx('No colors found.'),'hcc-library-empty'))}}
  function rgbToCmyk(r,g,b){var rr=r/255,gg=g/255,bb=b/255,k=1-Math.max(rr,gg,bb);if(k>=1)return {c:0,m:0,y:0,k:100};return {c:Math.round((1-rr-k)/(1-k)*100),m:Math.round((1-gg-k)/(1-k)*100),y:Math.round((1-bb-k)/(1-k)*100),k:Math.round(k*100)}}
  function converterValuesFromRgb(rgb){var hex=rgbToHex(rgb.r,rgb.g,rgb.b),hsl=rgbToHsl(rgb.r,rgb.g,rgb.b),hsv=rgbToHsv(rgb.r,rgb.g,rgb.b),ok=rgbToOklch(rgb.r,rgb.g,rgb.b),cmyk=rgbToCmyk(rgb.r,rgb.g,rgb.b);return {rgb:rgb,hex:hex,hsl:hsl,hsv:hsv,ok:ok,cmyk:cmyk,hexValue:'#'+hex,rgbValue:rgb.r+', '+rgb.g+', '+rgb.b,hslValue:hsl.h+', '+hsl.s+', '+hsl.l,hsvValue:Math.round(hsv.h)+', '+Math.round(hsv.s)+', '+Math.round(hsv.v),okValue:ok.l+', '+ok.c+', '+ok.h,cmykValue:cmyk.c+', '+cmyk.m+', '+cmyk.y+', '+cmyk.k,hexCss:'#'+hex,rgbCss:'rgb('+rgb.r+' '+rgb.g+' '+rgb.b+')',hslCss:'hsl('+hsl.h+' '+hsl.s+' '+hsl.l+')',hsvCss:'hsv('+Math.round(hsv.h)+' '+Math.round(hsv.s)+' '+Math.round(hsv.v)+')',okCss:'oklch('+ok.l+' '+ok.c+' '+ok.h+')'}}
  function converterBlank(rowsId,previewId){var rows=document.getElementById(rowsId||'hccConverterRows'),preview=document.getElementById(previewId||'hccConverterPreview');clear(rows);preview.className='hcc-converter-preview';preview.style.setProperty('--converter-color','#fff');preview.style.setProperty('--converter-text','#606876');preview.textContent=tx('Enter a color code above');preview.onclick=null;['Hex','RGB','HSL','HSV','OKLCH','CMYK'].forEach(function(label){var row=block('tr');row.appendChild(textNode('td',label));row.appendChild(textNode('td','--'));row.appendChild(textNode('td',label==='CMYK'?'':'--'));rows.appendChild(row)})}
  function converterCell(text,rgb,copyValue){var td=block('td');if(text){var span=textNode('span',text,'hcc-converter-code');span.onclick=function(){setFromRgb(rgb);copyText(copyValue||text)};td.appendChild(span)}else{td.textContent=text===''?'':'--'}return td}
  function renderConverterResult(rgb,rowsId,previewId){rgb={r:Math.round(clamp(Number(rgb.r)||0,0,255)),g:Math.round(clamp(Number(rgb.g)||0,0,255)),b:Math.round(clamp(Number(rgb.b)||0,0,255))};var v=converterValuesFromRgb(rgb),preview=document.getElementById(previewId),rows=document.getElementById(rowsId);syncColorState(rgb);render();preview.className='hcc-converter-preview has-color';preview.style.setProperty('--converter-color',v.hexValue);preview.style.setProperty('--converter-text',lum(rgb)>.55?'#000':'#fff');preview.textContent=v.hexValue;preview.onclick=function(){setFromRgb(rgb);copyText(v.hexValue)};clear(rows);[['Hex',v.hexValue,v.hexCss],['RGB',v.rgbValue,v.rgbCss],['HSL',v.hslValue,v.hslCss],['HSV',v.hsvValue,v.hsvCss],['OKLCH',v.okValue,v.okCss],['CMYK',v.cmykValue,'']].forEach(function(r){var row=block('tr');row.appendChild(textNode('td',r[0]));row.appendChild(converterCell(r[1],rgb,r[1]));row.appendChild(converterCell(r[2],rgb,r[2]));rows.appendChild(row)})}
  function updateConverterFromRgb(){var r=document.getElementById('hccConvR').value,g=document.getElementById('hccConvG').value,b=document.getElementById('hccConvB').value;if(r===''||g===''||b===''){converterBlank();return}renderConverterResult({r:r,g:g,b:b},'hccConverterRows','hccConverterPreview')}
  function resetConverter(){document.getElementById('hccConvR').value='';document.getElementById('hccConvG').value='';document.getElementById('hccConvB').value='';converterBlank('hccConverterRows','hccConverterPreview')}
  function updateHexRgbFromHex(){var rgb=hexToRgb(document.getElementById('hccHexRgbInput').value);if(!rgb){converterBlank('hccHexRgbRows','hccHexRgbPreview');return}renderConverterResult(rgb,'hccHexRgbRows','hccHexRgbPreview')}
  function resetHexRgb(){document.getElementById('hccHexRgbInput').value='';converterBlank('hccHexRgbRows','hccHexRgbPreview')}
  function normContrastHexInput(id,fallback){var el=document.getElementById(id),rgb=hexToRgb(el.value);if(!rgb){rgb=hexToRgb(fallback||'808080')}el.value=rgbToHex(rgb.r,rgb.g,rgb.b);return rgb}
  function contrastMark(ok){var s=block('span','hcc-contrast-mark '+(ok?'pass':'fail'));s.innerHTML=ok?'&#10003;':'&times;';return s}
  function maybeRenderContrastInput(id){var v=cleanHex(document.getElementById(id).value);if(v.length===3||v.length===6){renderContrastTool()}}
  function setContrastFromLight(kind){var id=kind==='fg'?'hccContrastFg':'hccContrastBg',lid=kind==='fg'?'hccContrastFgLight':'hccContrastBgLight',rgb=normContrastHexInput(id,kind==='fg'?'8A3030':'FFFFFF'),hsl=rgbToHsl(rgb.r,rgb.g,rgb.b),next=hslToRgb(hsl.h,hsl.s,Number(document.getElementById(lid).value)||0);document.getElementById(id).value=rgbToHex(next.r,next.g,next.b);renderContrastTool()}
  function renderContrastTool(){var fg=normContrastHexInput('hccContrastFg','8A3030'),bg=normContrastHexInput('hccContrastBg','FFFFFF'),ratio=shared.contrastRatio(fg,bg),preview=document.getElementById('hccContrastPreview'),rows=document.getElementById('hccContrastToolRows'),fgHex=rgbToHex(fg.r,fg.g,fg.b),bgHex=rgbToHex(bg.r,bg.g,bg.b),fgHsl=rgbToHsl(fg.r,fg.g,fg.b),bgHsl=rgbToHsl(bg.r,bg.g,bg.b);syncColorState(fg);render();document.getElementById('hccContrastFgSwatch').style.setProperty('--contrast-color','#'+fgHex);document.getElementById('hccContrastBgSwatch').style.setProperty('--contrast-color','#'+bgHex);document.getElementById('hccContrastFgLight').value=fgHsl.l;document.getElementById('hccContrastBgLight').value=bgHsl.l;document.getElementById('hccContrastFgLight').style.setProperty('--range-pct',fgHsl.l+'%');document.getElementById('hccContrastBgLight').style.setProperty('--range-pct',bgHsl.l+'%');document.getElementById('hccContrastFgLightLabel').textContent=tx('Lightness')+' ('+fgHsl.l+'%)';document.getElementById('hccContrastBgLightLabel').textContent=tx('Lightness')+' ('+bgHsl.l+'%)';preview.style.setProperty('--contrast-accent','#'+fgHex);preview.innerHTML='<span>'+ratio.toFixed(2)+'</span>';preview.onclick=function(){copyText(ratio.toFixed(2))};document.getElementById('hccContrastFgSwatch').onclick=function(){recordClickedHex(fgHex)};document.getElementById('hccContrastBgSwatch').onclick=function(){recordClickedHex(bgHex)};clear(rows);[[tx('Small text'),ratio>=4.5,ratio>=7],[tx('Large text'),ratio>=3,ratio>=4.5],[tx('UI element'),ratio>=3,ratio>=3]].forEach(function(r){var tr=block('tr');tr.appendChild(textNode('td',r[0]));var aa=block('td'),aaa=block('td');aa.appendChild(contrastMark(r[1]));aaa.appendChild(contrastMark(r[2]));tr.appendChild(aa);tr.appendChild(aaa);rows.appendChild(tr)})}
  function normMixerHexInput(id,fallback){var el=document.getElementById(id),rgb=hexToRgb(el.value);if(!rgb){rgb=hexToRgb(fallback||'808080')}el.value=rgbToHex(rgb.r,rgb.g,rgb.b);return rgb}
  function maybeRenderMixerInput(id){var v=cleanHex(document.getElementById(id).value);if(v.length===3||v.length===6){renderMixerTool()}}
  function mixerPaletteColors(a,b,balance,steps){var colors=['#'+rgbToHex(a.r,a.g,a.b)],ratio=clamp(balance,0,100)/100;if(steps===1){var one=labMix(a,b,ratio);colors.push('#'+rgbToHex(one.r,one.g,one.b))}else{var unit=1/(steps+1);for(var i=1;i<=steps;i++){var t=2*ratio*i*unit,rgb=labMix(a,b,t);colors.push('#'+rgbToHex(rgb.r,rgb.g,rgb.b))}}colors.push('#'+rgbToHex(b.r,b.g,b.b));return colors}
  function renderMixerTicks(steps){var ticks=document.getElementById('hccMixerTicks');clear(ticks);for(var i=1;i<=18;i++){var s=block('span',i===steps?'active':'');s.textContent=i;ticks.appendChild(s)}}
  function renderMixerTool(){var a=normMixerHexInput('hccMixerColor1','EC253F'),b=normMixerHexInput('hccMixerColor2','25ECD1'),bal=clamp(Number(document.getElementById('hccMixerBalance').value)||50,0,100),steps=Math.round(clamp(Number(document.getElementById('hccMixerSteps').value)||9,1,18)),mixed=labMix(a,b,bal/100),bar=document.getElementById('hccMixerBar'),colors=mixerPaletteColors(a,b,bal,steps),aHex=rgbToHex(a.r,a.g,a.b),bHex=rgbToHex(b.r,b.g,b.b);syncColorState(mixed);render();document.getElementById('hccMixerColor1Swatch').style.setProperty('--mixer-color','#'+aHex);document.getElementById('hccMixerColor2Swatch').style.setProperty('--mixer-color','#'+bHex);document.getElementById('hccMixerBalance').style.setProperty('--range-pct',bal+'%');document.getElementById('hccMixerSteps').style.setProperty('--range-pct',((steps-1)/17*100)+'%');document.getElementById('hccMixerBalanceLabel').textContent=tx('Balance')+' ('+Math.round(bal)+'%)';document.getElementById('hccMixerColor1Swatch').onclick=function(){recordClickedHex(aHex)};document.getElementById('hccMixerColor2Swatch').onclick=function(){recordClickedHex(bHex)};renderMixerTicks(steps);clear(bar);colors.forEach(function(h){var rgb=hexToRgb(h),btn=block('button');btn.type='button';btn.style.setProperty('--swatch-bg',h);btn.style.setProperty('--swatch-text',lum(rgb)>.55?'#000':'#fff');btn.textContent=cleanHex(h);btn.onclick=function(val){return function(){recordClickedHex(val)}}(h);bar.appendChild(btn)});document.getElementById('hccMixerExport').onclick=function(){openExport(false,colors)}}
  function chartDefaultHex(def){var mainGroup=def.groups[0]||[],idx=Math.min(mainGroup.length-1,Math.max(0,Math.floor(mainGroup.length/2)));return mainGroup[idx]||mainGroup[0]||'808080'}
  function chartSelectedHex(def){return cleanHex(chartPicked[def.slug]||chartDefaultHex(def))}
  function chartMatrix(def,cls,fillShort){var grid=block('div',cls||'hcc-chart-matrix'),rows=0;def.groups.forEach(function(group){rows=Math.max(rows,group.length)});def.groups.forEach(function(group){if(fillShort&&group.length<Math.max(4,rows*.55))return;var col=block('div','hcc-chart-col'+(fillShort&&group.length<rows?' fill':''));group.forEach(function(hex){var rgb=hexToRgb(hex),cell=block('button','hcc-chart-cell');cell.type='button';cell.title='#'+hex;cell.style.backgroundColor='#'+hex;cell.style.setProperty('--cell-bg','#'+hex);cell.onclick=function(){chartPicked[def.slug]=hex;setFromRgb(rgb);recordClickedHex(hex)};col.appendChild(cell)});grid.appendChild(col)});return grid}
  function renderChart(){var defs=chartDefs(),mount=document.getElementById('hccChartTable');if(!mount||mount.getAttribute('data-ready')==='1')return;clear(mount);defs.forEach(function(def){var card=block('section','hcc-chart-card'),h=textNode('h2',tx(def.title)),p=textNode('p',tx(def.desc)),btn=block('button','hcc-chart-btn'),grid=chartMatrix(def,'hcc-chart-matrix',true);btn.type='button';btn.textContent=tx('Full chart');btn.onclick=function(){setChartDetail(def.slug,true)};card.appendChild(grid);card.appendChild(h);card.appendChild(p);card.appendChild(btn);mount.appendChild(card)});mount.setAttribute('data-ready','1')}
  function renderChartDetail(def){var mount=document.getElementById('hccChartTable'),wrap=block('section','hcc-chart-detail'),list=block('div','hcc-chart-list'),selected=chartSelectedHex(def);clear(mount);def.groups.forEach(function(group,idx){var fam=block('section','hcc-chart-family'),head=block('div','hcc-chart-family-head'),name=block('h3'),ex=block('button','hcc-link-btn'),bar=block('div','hcc-chart-family-bar'),colors=group.map(function(hex){return '#'+hex});name.textContent=(def.names&&def.names[idx])?tx(def.names[idx]):tx('Color '+(idx+1));ex.type='button';ex.appendChild(document.createTextNode(tx('Export')));ex.appendChild(exportSvg());ex.onclick=function(){openExport(false,colors)};head.appendChild(name);head.appendChild(ex);group.forEach(function(hex,i){var rgb=hexToRgb(hex),sw=block('button','hcc-chart-family-swatch'+(cleanHex(hex)===selected?' active':'')),label=block('span'),shade=(def.shades&&def.shades[i])?def.shades[i]:'';sw.type='button';sw.title='#'+hex;sw.style.backgroundColor='#'+hex;sw.style.setProperty('--cell-bg','#'+hex);sw.style.setProperty('--swatch-text',lum(rgb)>.55?'#000':'#fff');sw.style.setProperty('--chart-dot',lum(rgb)>.48?'#000':'#fff');if(shade){label.appendChild(textNode('b',shade))}label.appendChild(textNode('em',hex));sw.appendChild(label);sw.onclick=function(){chartPicked[def.slug]=hex;setFromRgb(rgb);renderChartDetail(def);recordClickedHex(hex)};bar.appendChild(sw)});fam.appendChild(head);fam.appendChild(bar);list.appendChild(fam)});wrap.appendChild(list);mount.appendChild(wrap);mount.setAttribute('data-ready','detail-'+def.slug)}
  function findChartDef(slug){var defs=chartDefs();for(var i=0;i<defs.length;i++){if(defs[i].slug===slug)return defs[i]}return null}
  function chartPathSlug(slug){return slug==='tailwind'?'chart-tailwind':(slug==='flat'?'chart-flat':(slug==='material'?'chart-material':(slug==='websafe'?'chart-websafe':'chart')))}
  function trackChartBars(){Array.prototype.slice.call(document.querySelectorAll('.hcc-chart-family-bar')).forEach(function(bar){if(bar.dataset.hoverLock)return;bar.dataset.hoverLock='1';function clearHover(){Array.prototype.slice.call(bar.querySelectorAll('.is-hovered')).forEach(function(i){i.classList.remove('is-hovered')})}bar.addEventListener('mousemove',function(e){var item=e.target&&e.target.closest?e.target.closest('.hcc-chart-family-swatch'):null;if(!item||!bar.contains(item))return;if(item.classList.contains('is-hovered'))return;clearHover();item.classList.add('is-hovered')});bar.addEventListener('mouseleave',clearHover)})}
  function setChartDetail(slug,syncHash){var def=findChartDef(slug);if(!def){setChartPage(syncHash);return}setActiveRoute(chartPathSlug(slug));if(syncHash){setRoute(chartPathSlug(slug),true)}var mainHex=chartSelectedHex(def);if(mainHex){syncColorState(hexToRgb(mainHex))}document.querySelector('.hcc-app').className='hcc-app chart-mode chart-detail-mode';clearTopNav();document.getElementById('hccNavChart').className='active';document.querySelector('.hcc-crumb').textContent=t('page.crumbColor');document.querySelector('.hcc-hero h1').textContent=tx(def.title);document.querySelector('.hcc-hero p').textContent=tx(def.desc);render();renderChartDetail(def);trackChartBars()}
  function setChartPage(syncHash){setActiveRoute('chart');if(syncHash){setRoute('chart',false)}var mount=document.getElementById('hccChartTable');if(mount)mount.setAttribute('data-ready','');document.querySelector('.hcc-app').className='hcc-app chart-mode';clearTopNav();document.getElementById('hccNavChart').className='active';setHeroText(t('page.crumbColor'),t('page.chartTitle'),t('page.chartDesc'));render();renderChart()}
  function setLibraryPage(syncHash){setActiveRoute('library');if(syncHash){setRoute('library',false)}document.querySelector('.hcc-app').className='hcc-app library-mode';clearTopNav();document.getElementById('hccNavLibrary').className='active';setHeroText(t('page.crumbColor'),t('page.libraryTitle'),t('page.libraryDesc'));render();renderLibrary()}
  function setConverterPage(syncHash){setActiveRoute('converter');if(syncHash){setRoute('converter',false)}document.querySelector('.hcc-app').className='hcc-app converter-mode';clearTopNav();document.getElementById('hccNavConverter').className='active';document.getElementById('hccNavRgbHexItem').className='active';setHeroText(t('page.crumbColor'),t('page.rgbTitle'),t('page.rgbDesc'));render();converterBlank('hccConverterRows','hccConverterPreview')}
  function setHexRgbPage(syncHash){setActiveRoute('hex-to-rgb');if(syncHash){setRoute('hex-to-rgb',false)}document.querySelector('.hcc-app').className='hcc-app hexrgb-mode';clearTopNav();document.getElementById('hccNavConverter').className='active';document.getElementById('hccNavHexRgbItem').className='active';setHeroText(t('page.crumbColor'),t('page.hexTitle'),t('page.hexDesc'));render();converterBlank('hccHexRgbRows','hccHexRgbPreview')}
  function setContrastToolPage(syncHash){setActiveRoute('contrast-checker');if(syncHash){setRoute('contrast-checker',false)}document.querySelector('.hcc-app').className='hcc-app contrast-tool-mode';clearTopNav();document.getElementById('hccNavTools').className='active';document.getElementById('hccNavContrastItem').className='active';setHeroText(t('page.crumbTools'),t('page.contrastTitle'),t('page.contrastDesc'));renderContrastTool()}
  function setMixerPage(syncHash){setActiveRoute('color-mixer');if(syncHash){setRoute('color-mixer',false)}document.querySelector('.hcc-app').className='hcc-app mixer-mode';clearTopNav();document.getElementById('hccNavTools').className='active';document.getElementById('hccNavMixerItem').className='active';setHeroText(t('page.crumbTools'),t('page.mixerTitle'),t('page.mixerDesc'));renderMixerTool()}
  window.HCC_REGISTER_PAGES_EXTRA(function(){
    return {
      setNamePage:function(kind,syncHash){ensureNameData(function(){setNamePage(kind,syncHash)})},
      renderLibrary:function(){ensureLibraryData(renderLibrary)},
      updateConverterFromRgb:updateConverterFromRgb,
      resetConverter:resetConverter,
      updateHexRgbFromHex:updateHexRgbFromHex,
      resetHexRgb:resetHexRgb,
      maybeRenderContrastInput:maybeRenderContrastInput,
      renderContrastTool:renderContrastTool,
      setContrastFromLight:setContrastFromLight,
      renderMixerTool:renderMixerTool,
      maybeRenderMixerInput:maybeRenderMixerInput,
      setLibraryPage:function(syncHash){ensureLibraryData(function(){setLibraryPage(syncHash)})},
      setConverterPage:setConverterPage,
      setHexRgbPage:setHexRgbPage,
      setContrastToolPage:setContrastToolPage,
      setMixerPage:setMixerPage,
      setChartDetail:function(slug,syncHash){ensureChartData(function(){setChartDetail(slug,syncHash)})},
      setChartPage:function(syncHash){ensureChartData(function(){setChartPage(syncHash)})}
    };
  });
})();
